### ISSUE TITLE
Error (exit status 127)

### ISSUE THREAD

**Issue by aeosynth** [kristijanhusak/vim-packager#1]
When running `packager#update()`, I get this error for already installed packages.

First issue :tada:

**Comment by kristijanhusak** [comment]
Go to that plugin line and press `E`, you should see stdout in preview window.

**Comment by aeosynth** [comment]
```
fish: Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
cd /home/james/.config/nvim/pack/packager/opt/vim-packager && git pull --ff-only --progress
```

need fish support

**Comment by kristijanhusak** [comment]
I fixed it, it will now use `sh` to run the commands, and restore to the default shell after running the commands.
