### ISSUE TITLE
Switching from minpac, slow startup

### ISSUE THREAD

**Issue by ahmedelgabri** [kristijanhusak/vim-packager#10]
This might not be a plugin issue, maybe it's more how my config is set up. But I hope I can find some pointers on how to fix this.

This is my current setup with [`minpac`](https://github.com/ahmedelgabri/dotfiles/blob/e78429fad33fa2e1c5940843eff007d9dbc6cc9b/files/.vim/autoload/plugins.vim) & `plugins#init()` is called in [`init.vim`](https://github.com/ahmedelgabri/dotfiles/blob/e78429fad33fa2e1c5940843eff007d9dbc6cc9b/files/.vim/init.vim#L47)

This is the new setup with [`vim-packager`](https://github.com/ahmedelgabri/dotfiles/blob/7e5b93eef73c7e2912aaa161aef992606f35f979/files/.vim/autoload/plugins.vim) as you can see nothing much changed, it's a drop-in replacement for minpac.

I'm facing an issue with [this line](https://github.com/ahmedelgabri/dotfiles/blob/7e5b93eef73c7e2912aaa161aef992606f35f979/files/.vim/autoload/plugins.vim#L144) which runs every time I open neovim. With `minpac` there is nearly no overhead & things are instantaneous but with `vim-packager` this takes a couple of seconds. 

minpac
![minpac](https://user-images.githubusercontent.com/63876/69666221-33475480-108c-11ea-9ab8-e90bdc369110.gif)

vim-packager
![vim-packager](https://user-images.githubusercontent.com/63876/69666572-be284f00-108c-11ea-9863-f18ab4a6906d.gif)

**Comment by kristijanhusak** [comment]
Yeah i noticed the same thing. Had plans to optimize it, just didn't grab enough time. 

Solution to this is to not call init every time. Is there any specific reason you do that? Having it loaded only when needed should do the trick, and it won't slow anything down.

**Comment by ahmedelgabri** [comment]
> Yeah i noticed the same thing. Had plans to optimize it, just didn't grab enough time.

Great, thanks. I'll wait for this then.



> Solution to this is to not call init every time. Is there any specific reason you do that? Having it loaded only when needed should do the trick, and it won't slow anything down.

`plugins#init()` is an autoloaded function so if I don't call it, then [`commands`](https://github.com/ahmedelgabri/dotfiles/blob/7e5b93eef73c7e2912aaa161aef992606f35f979/files/.vim/autoload/plugins.vim#L10-L12) won't work properly because no plugin will be loaded including `vim-packager` or `minpac`. Or am I missing something here?

**Comment by kristijanhusak** [comment]
Plugins are automatically loaded, at least those that are not in the `opt` folder. That's the main feature of minpac/vim-packager. Vim/NeoVim does the loading, no need to do it manually like in vim-plug.

Check the example vimrc content here in readme https://github.com/kristijanhusak/vim-packager#vimrc-content

With those commands in the example, function loads up vim-packager and all the plugins for installation/update/clean.

This means that only when running install/update/clean things will take a second or two, but that's not really that bad.

**Comment by ahmedelgabri** [comment]
> Plugins are automatically loaded, at least those that are not in the `opt` folder. That's the main feature of minpac/vim-packager. Vim/NeoVim does the loading, no need to do it manually like in vim-plug.

You are right, I dunno why I did this in the first place… will clean this up & see.

**Comment by ahmedelgabri** [comment]
Fixing [`plugins#init()`](https://github.com/ahmedelgabri/dotfiles/blob/d5fee667296c21eb5f30c2f8d8f33654f481703c/files/.vim/autoload/plugins.vim#L138-L144)& the [commands](https://github.com/ahmedelgabri/dotfiles/blob/d5fee667296c21eb5f30c2f8d8f33654f481703c/files/.vim/autoload/plugins.vim#L10-L12) fixed the issue.

FYI, `PackagerClean` or `PackagerStatus` are slower than `minpac` too. Not a big deal at all, but worth mentioning. 

Thank you

**Comment by kristijanhusak** [comment]
@ahmedelgabri I optimized it a bit. Do an update and check. Should be faster now.
I still don't suggest calling `plugins#init()` on vim startup, because there's no really a need for it.

**Comment by ahmedelgabri** [comment]
> @ahmedelgabri I optimized it a bit. Do an update and check. Should be faster now.

Slightly better yeah, thanks!

> I still don't suggest calling `plugins#init()` on vim startup, because there's no really a need for it.

The idea behind `plugins#init()` was to auto install packages when I initially setup a new machine (_I know that I can do `nvim +PackInstall`, but I'm lazy & I know that I will forget doing this on a new machine_), the implementation though was bad. So I will need to revisit that. Right now I changed the logic to [exit early](https://github.com/ahmedelgabri/dotfiles/blob/20cb5a94ece893071288a5beccafc4211a04c772/files/.vim/autoload/plugins.vim#L139-L141) so it's just a simple check.
