### ISSUE TITLE
status doesn't show any commits for updated plugins

### ISSUE THREAD

**Issue by ahmedelgabri** [kristijanhusak/vim-packager#11]
Since `vim-packager` seems to share lots of things with `minpac` I assume it's having the same issue also https://github.com/k-takata/minpac/issues/76

**Comment by kristijanhusak** [comment]
Did you give it a try?

Works fine for me:

![screenshot](https://i.imgur.com/kUcefD2.png)

**Comment by ahmedelgabri** [comment]
I have already tried & that's why I opened the issue. Will post a screenshot when I have access to my laptop again.

**Comment by ahmedelgabri** [comment]
Both of these plugins got updated today & that's all I can see for example

<img width="490" alt="Screenshot 2019-12-01 at 13 02 38" src="https://user-images.githubusercontent.com/63876/69913663-fa680080-143a-11ea-82dd-354b6f7351d2.png">

 When I run the same command as in https://github.com/kristijanhusak/vim-packager/blob/5707582df80b9d3fbdd5e0620664c73e6fc8f4c7/autoload/packager/plugin.vim#L129-L131  I don't get anything, while it's very clear that they have new updates if I `cd` into the directories & do a normal `git log`

<img width="872" alt="Screenshot 2019-12-01 at 13 06 24" src="https://user-images.githubusercontent.com/63876/69913706-972a9e00-143b-11ea-938c-9770aeae143a.png">

**Comment by kristijanhusak** [comment]
I need few things to try to figure this out:

First, give me your git version (`git --version`)

Second, i need you to do these steps:
1. Go to vim-fugitive folder, do `git reset --hard dc53206`
2. Open vim, do `PackagerUpdate`
3. Restart vim
4. do a `PackagerStatus`
5. Give me screenshot of status buffer

**Comment by ahmedelgabri** [comment]
> First, give me your git version (`git --version`)

`git version 2.24.0`



> Second, i need you to do these steps:
> 
> 1. Go to vim-fugitive folder, do `git reset --hard dc53206`
> 2. Open vim, do `PackagerUpdate`
> 3. Restart vim
> 4. do a `PackagerStatus`
> 5. Give me screenshot of status buffer

<img width="988" alt="Screenshot 2019-12-01 at 18 11 40" src="https://user-images.githubusercontent.com/63876/69917434-49775b00-1466-11ea-9522-2cee2c7d1c91.png">

**Comment by kristijanhusak** [comment]
That's really strange. What you get if you do a git log like this in vim-fugitive folder:
```
git log HEAD@{1}..
```

**Comment by ahmedelgabri** [comment]
Both return nothing…

**Comment by ahmedelgabri** [comment]
Changing it to `git log HEAD@{2}..` works though, but nothing is returned with `HEAD@{1}`

**Comment by kristijanhusak** [comment]
What's the result of the `HEAD@{2}..` ?

**Comment by ahmedelgabri** [comment]
<img width="823" alt="Screenshot 2019-12-01 at 18 49 12" src="https://user-images.githubusercontent.com/63876/69917898-62ced600-146b-11ea-9230-2955c9edb9ec.png">

**Comment by kristijanhusak** [comment]
That should be the result of `HEAD@{1}..`.

Can you give me your .gitconfig file?

**Comment by ahmedelgabri** [comment]
Here is my [`.gitconfig`](https://github.com/ahmedelgabri/dotfiles/blob/27d5058404d7d27947751c3eee48c8796353e10a/files/.gitconfig) 

`git reflog` for `vim-fugitive` folder

```
671a85d (HEAD -> master, origin/master, origin/HEAD) HEAD@{0}: rebase finished: refs/heads/master onto 671a85dabaed7e21aa7e435adfdad9b9461cb7d8
671a85d (HEAD -> master, origin/master, origin/HEAD) HEAD@{1}: pull --ff-only --progress: checkout 671a85dabaed7e21aa7e435adfdad9b9461cb7d8
dc53206 HEAD@{2}: reset: moving to dc53206
671a85d (HEAD -> master, origin/master, origin/HEAD) HEAD@{3}: rebase finished: refs/heads/master onto 671a85dabaed7e21aa7e435adfdad9b9461cb7d8
671a85d (HEAD -> master, origin/master, origin/HEAD) HEAD@{4}: pull --ff-only --progress: checkout 671a85dabaed7e21aa7e435adfdad9b9461cb7d8
67efbf6 HEAD@{5}: clone: from https://github.com/tpope/vim-fugitive
```

**Comment by kristijanhusak** [comment]
Ok, i'm pretty sure it has to do something with this part of gitconfig:
```
[pull]
  rebase = true
```

Try to apply this patch to vim-packager:

```diff
diff --git a/autoload/packager/plugin.vim b/autoload/packager/plugin.vim
index 844fd06..fcc290a 100644
--- a/autoload/packager/plugin.vim
+++ b/autoload/packager/plugin.vim
@@ -65,7 +65,7 @@ function! s:plugin.update_git_command() abort
   endif
 
   if l:is_on_branch
-    let l:update_cmd += ['&&', 'git', 'pull', '--ff-only', '--progress']
+    let l:update_cmd += ['&&', 'git', 'pull', '--ff-only', '--progress', '--rebase=false']
   else
     let l:update_cmd += ['&&', 'git', 'fetch', self.url]
   endif

```


And then do the same steps like in the [previous comment](https://github.com/kristijanhusak/vim-packager/issues/11#issuecomment-560130858)

to see if it works.

**Comment by ahmedelgabri** [comment]
Yes, this patch seems to fix the issue.

**Comment by kristijanhusak** [comment]
Ok, thanks.

I pushed the fix, do an update, and from now on every update should appear for you.

**Comment by ahmedelgabri** [comment]
Perfect! thank you very much.
