### ISSUE TITLE
`Too many open files: "sh"` error since 234249d

### ISSUE THREAD

**Issue by deathlyfrantic** [kristijanhusak/vim-packager#13]
Since commit 234249d I'm getting the following error when trying add my plugins to Packager using `packager#add()`:

```
Error detected while processing function <SNR>15_packager_init[8]..packager#add[2]..17[1]..packager#plugin#new[1]..37[20]..48[1]..packager#utils#system_async[9]..packager#job#start[1]..<SNR>78_job_start:
line   30:
E903: Process failed to start: too many open files: "sh"
```

Commit 86be118 is the last one that works without this error. I have 41 plugins. I'm using Neovim on macOS 10.14.6.

**Comment by kristijanhusak** [comment]
I pushed a fix. Pull latest master and give it a try.

**Comment by deathlyfrantic** [comment]
Works now, thanks!
