### ISSUE TITLE
vim-packager removes itself when running PackagerClean

### ISSUE THREAD

**Issue by Arelav** [kristijanhusak/vim-packager#16]
vim-packager removes itself when running PackagerClean

I get this:
"Clean up [$MY_HOME]/.config/nvim/pack/packager/opt/vim-packager — Waiting for confirmation..."

This is the part of my config.
```viml
function! PackagerInit() abort
  packadd vim-packager
  call packager#init()

  call packager#add(...
endfunction

command! PackagerInstall call PackagerInit() | call packager#install()
command! -bang PackagerUpdate call PackagerInit() | call packager#update({ 'force_hooks': '<bang>' })
command! PackagerClean call PackagerInit() | call packager#clean()
command! PackagerStatus call PackagerInit() | call packager#status()
```

**Comment by kristijanhusak** [comment]
Do you have vim packager itself added as a package?
```
call packager#add('kristijanhusak/vim-packager', { 'type': 'opt' })
```
You didn't paste any of packages here.

**Comment by Arelav** [comment]
Thanks. That was an issue. My bad.
I was comparing with plug and last time put the packages I used in plug not as in documentation.
Please close the issue.

**Comment by Arelav** [comment]
And thanks for so fast feedback.

**Comment by kristijanhusak** [comment]
No problem. Closing.
