### ISSUE TITLE
runtimepath is not added automatically for all plugins 

### ISSUE THREAD

**Issue by zachliu** [kristijanhusak/vim-packager#17]
through reasons i have yet known, certain plugins like `lambdalisue/gina.vim` still requires the following to be done manually :thinking: 
```
set runtimepath+=~/.config/nvim/pack/packager/start/gina.vim
```
otherwise it's not recognized

**Comment by kristijanhusak** [comment]
I'll check. Did you try `packadd gina.vim`?

**Comment by zachliu** [comment]
yeah, no luck

**Comment by kristijanhusak** [comment]
@zachliu I see in the related issue that you are trying to call gina function from your vimrc. Problem is that at that moment when you call the function gina is not loaded, because native vim packages load them asynchronously (vimrc first, and then plugins).

This should work for you:
```vimL
autocmd VimEnter * call s:setup_gina()

function! s:setup_gina() abort
  for gina_cmd in ['branch', 'changes', 'log', 'commit', 'status']
    call gina#custom#command#option(gina_cmd, '--opener', 'tabedit')
  endfor

  for gina_cmd in ['diff']
    call gina#custom#command#option(gina_cmd, '--opener', 'vsplit')
  endfor

  call gina#custom#command#option('commit', '--verbose')
  call gina#custom#command#option('branch', '--verbose|--all')
endfunction
```

**Comment by zachliu** [comment]
oooohhh, right, how did i forget the async :man_facepalming: 
thank you so much!

**Comment by zachliu** [comment]
this may or may not be related, but i found that i also had to put
```
  autocmd FileType python syntax keyword pythonBuiltinObj self
```
in that function otherwise the autocmd does nothing, which makes little sense here :thinking:

**Comment by kristijanhusak** [comment]
where did you find this information?

**Comment by zachliu** [comment]
it's part of my customized syntax highlighting

**Comment by kristijanhusak** [comment]
I don't know what syntax highligthing has to do to with gina plugin. What is `self` in this? Never saw something like that.
Are you using vim or neovim? Do you have filetype plugin indent on in your vimrc?

All of this is not related to packager because it doesn't do anything besides installing / updating packages to folder that is auto loaded by vim.

**Comment by zachliu** [comment]
i'm using `neovim` and i have `filetype plugin indent on`
my guess is a rogue plugin is overwriting my `autocmd FileType ....`

**Comment by zachliu** [comment]
btw, 
```
autocmd FileType python syntax keyword pythonBuiltinObj self
```
means when the `set ft=python` event happens, the python key word `self` shall be colored (highlighted) as `pythonBuiltinObj` which is a category of keyword :grin:

**Comment by kristijanhusak** [comment]
ah, `self` is a keyword :D I thought it is a reference to the vim function or something :D 
I'm not sure why that happens, but it's not related to vim packager.
