### ISSUE TITLE
Add setting to default to 'opt' type

### ISSUE THREAD

**Issue by comfortablynick** [kristijanhusak/vim-packager#18]
Thanks for the plugin, I think it's the best way to manage vim packages right now. I currently have a shim function that sets the plugins to `{'type': 'opt'}` by default. I was wondering if there is any interest in incorporating this into the plugin.

I generally only put filetype plugins in 'start', but maybe my usage is not common.

**Comment by kristijanhusak** [comment]
Yeah, i added it. Pass the default `type` to `packager#init` like this:

```vimL
call packager#init({'default_plugin_type': 'opt'})
```

Let me know if it works.

**Comment by comfortablynick** [comment]
Wow, that was fast! It works great, thank you.
