### ISSUE TITLE
Document using 'git@' SSH URLs for packages user may want to modify

### ISSUE THREAD

**Issue by andrewferrier** [kristijanhusak/vim-packager#20]
I maintain a few git plugins myself. It's not documented, but I tried using `git@github.com:...` style URLs (as generated by GitHub when you select the 'Clone via SSH' option, and they worked! This is an incredibly useful resource for any plugin author, or anyone who plans to fork and modify a plugin.

I suggest documenting this in the README, perhaps with an example. I'd be happy to send in a pull req if you're interested.

**Comment by andrewferrier** [comment]
And thanks for all your hard work on `vim-packager`, great tool ;)

**Comment by kristijanhusak** [comment]
PR is very welcome :)

**Comment by andrewferrier** [comment]
Great. See pull request #21 . Thanks!
