### ISSUE TITLE
The ability to get plugin list

### ISSUE THREAD

**Issue by Shatur95** [kristijanhusak/vim-packager#23]
Minpack have `minpac#getpluglist` and `minpac#getpluginfo`. In very convenient for scripting. Could you add a the same API?

**Comment by kristijanhusak** [comment]
Sure, why not.

**Comment by kristijanhusak** [comment]
@Shatur95 I introduced `packager#plugins()` and `packager#plugin(plugin_name)` functions. Just make sure to call `PackagerInit` function before trying them, to populate the plugins list and add packager to runtime.
I didn't document it yet, will wait for your feedback.

**Comment by Shatur95** [comment]
Thanks! Could you add also something like `packager#plugin_names()`? I think this can me more common case.

**Comment by kristijanhusak** [comment]
You have the name for each plugin here. Just map it out for yourself however you need it.

**Comment by Shatur95** [comment]
Of course, but getting all information is a bit slow. It would be nice to have the ability to get only names and then get information about specific plugin.

**Comment by kristijanhusak** [comment]
Yeah, it's a bit slower because it needs to do some git calls to fetch all the data.
I added `packager#plugin_names()` that returns only list of names.

**Comment by Shatur95** [comment]
Thank you, now much faster!

I wrote the following helper for myself, maybe someone will find it useful:

```vim
function! OpenPackageFolder(plugin_name)
  if has('win32')
    let program = 'start '
  else
    let program = 'xdg-open '
  endif
  call system(program . packager#plugin(a:plugin_name).dir)
endfunction

function! FzfPackages()
  call PackagerInit()
  call fzf#run(fzf#wrap({'source': packager#plugin_names(), 'sink': function('OpenPackageFolder')}))
endfunction
```
