### ISSUE TITLE
Cannot install a plugin as an optional

### ISSUE THREAD

**Issue by vaklinzi** [kristijanhusak/vim-packager#24]
Thank you for the great package manager. It's fast and simple and I just love it. I just have one problem when trying to install some plugins as an optional type. One such example is `https://github.com/iamcco/markdown-preview.nvim` which I added like this:

`  call packager#add('iamcco/markdown-preview.nvim', {'do': 'sh -c "cd app & yarn install"', 'type': 'opt'})`

and then:

```
augroup packager_filetype
  autocmd!
  autocmd FileType markdown packadd markdown-preview
augroup END

```
but when I open a markdown file, all the commands for this plugin are missing. I had the same problem with few other plugins with optional type (but not will all) so maybe I am missing something.

**Comment by kristijanhusak** [comment]
try `packadd markdown-preview.nvim`

**Comment by Shatur95** [comment]
I use the following:

```vim
  call packager#add('iamcco/markdown-preview.nvim', {'type': 'opt', 'do': 'packadd markdown-preview.nvim | call mkdp#util#install()'})
```

**Comment by kristijanhusak** [comment]
No need to do packadd in the `do`. This should work fine:
```
call packager#add('iamcco/markdown-preview.nvim', {'type': 'opt', 'do': ':call mkdp#util#install()'})
```

Note the `:` at the beginning of the `do` value. This tells packager it's a vim command.
you don't need to do packadd because packager adds it to runtime after install/update.

**Comment by Shatur95** [comment]
Did not know, thank you!

**Comment by kristijanhusak** [comment]
Everything ok? Can we close this?

**Comment by Shatur95** [comment]
I have the same plugin as the author of the issue and your approach is works for me.

**Comment by vaklinzi** [comment]
No, it's still doesn't work. If I set `packadd markdown-preview.nvim` it will be added for every filetype. I don't need that. Why will I use opt if I can specify for which type it should be active? For most of the plugins filetype specification works but this is one example where it doesn't work.

**Comment by Shatur95** [comment]
@vaklinzi, to enable it for specific type I to calling `:packadd ...` in [ftplugin](https://github.com/Shatur95/neovim-config/blob/master/after/ftplugin/markdown.vim).

**Comment by kristijanhusak** [comment]
@vaklinzi i meant to do that in the autocmd like you did, just append `.nvim`
