### ISSUE TITLE
Disable default mappings

### ISSUE THREAD

**Issue by Shatur95** [kristijanhusak/vim-packager#25]
Could add an option to disable default mappings?

**Comment by kristijanhusak** [comment]
@Shatur95 If you add your own, nothing will be set. For example, If you add this to your vimrc:

```
autocmd FileType packager nmap <buffer> <C-h> <Plug>(PackagerGotoNextPlugin)
```

Go to next plugin mapping which is by default `<C-j>` won't be mapped.

**Comment by Shatur95** [comment]
Can I remove mapping in this way? For example, I do not need `<Plug>(PackagerQuit)` because I have universal shortcut `<C-q>` to close buffer.

**Comment by kristijanhusak** [comment]
do you use `q` for something else?

**Comment by Shatur95** [comment]
I use `<C-q>`. Because of this I would like to have the ability to remove `<Plug>(PackagerQuit)`. The most simple way - just remove all mappings and map only needed.

**Comment by Shatur95** [comment]
Most of the plugins have something like `g:packager#disable_default_mappings`. For example, [fern.vim](https://github.com/lambdalisue/fern.vim/blob/c92174fdc162c2c6185d6028fcaee0722c394b56/doc/fern.txt#L282), [vim-swap](https://github.com/machakann/vim-swap/blob/e52ff679c88f4aa7a7afe77fb42af78c93ed33c8/doc/swap.txt#L107).

**Comment by kristijanhusak** [comment]
I added it as an option to init. So when calling packager#init, do it like this:
```
  call packager#init({ 'disable_default_mappings': 1 })
```

**Comment by Shatur95** [comment]
Thank you a lot!

Could you remove the following text in status window in this case?
![изображение](https://user-images.githubusercontent.com/22453358/83627496-ae3f7980-a59f-11ea-8171-eae1b50e849a.png)

**Comment by kristijanhusak** [comment]
I don't see a reason. You know that you disabled the mappings and that they will not work.

**Comment by Shatur95** [comment]
Maybe just add an option to disable this label?
Something like [NERDTreeMinimalUI](https://github.com/preservim/nerdtree/blob/d48ab70721d4f688ed34bd5939e2d6f4c89548c5/doc/NERDTree.txt#L1145)?

**Comment by kristijanhusak** [comment]
I can add it, i'm just trying to understand why it bothers you? I'm spending maybe like max 1 min in the packager window, not looking at it all the time.

**Comment by Shatur95** [comment]
I just suggested because it displays wrong mappings even if I leave defaults and remap one of the displayed mappings. It just a little confusing :) I'd removed it. Of course, it's not important at all.
Thanks again!
