### ISSUE TITLE
E117 on `:PackagerUpdate`

### ISSUE THREAD

**Issue by n0542344** [kristijanhusak/vim-packager#26]
Thanks for the awesome vim-packager! I switched recently from minpac (https://github.com/k-takata/minpac) to packager and am enjoying your plugin manager very much!

Nevertheless I'm having an issue: while running `:PackagerUpdate` I'm getting the following error: 

    Error detected while processing function <lambda>5[1]..35:
    line   18:
    E117: Unknown function: setbufline

But the updating process seems to work (at least the most recent repository versions are pulled). The other commands (`:PackagerStatus`, `:PackagerInstall`) seem to work fine.

The relevant section from my '~/.config/nvim/init.vim' are:

---

    function! PackagerInit() abort
      packadd vim-packager
      call packager#init()
      call packager#add('kristijanhusak/vim-packager', { 'type': 'opt' })

      call packager#add('https://github.com/tpope/vim-vinegar')

      " ...

    endfunction

    command!        PackagerInstall call    PackagerInit() | call packager#install()
    command! -bang  PackagerUpdate  call    PackagerInit() | call packager#update({ 'force_hooks': '<bang>' })
    command!        PackagerClean   call    PackagerInit() | call packager#clean()
    command!        PackagerStatus  call    PackagerInit() | call packager#status()

---

I'm using nvim v0.3.4 on a Debian-based OS (PureOS 9.0 amber).

Any ideas?

**Comment by kristijanhusak** [comment]
Recently I did some changes and introduced usage of some internal functions that are probably missing on older versions.
Why are you using that old version of nvim?

**Comment by n0542344** [comment]
Wow, that was a fast reply - thanks for that!

The current version of PureOS is based upon Debian Stable (currently: Debian 10, Buster ) and there the providee version of neovim is 0.3.4-3 (https://packages.debian.org/search?keywords=neovim). 

Is there a way to get version which can be used for older nvim-versions? Should I clone a specific branch or tag of your repo?

But just for protocol: I'm using vim-packager for the first time, so I cannot say that this is due to a change that happened recently.

**Comment by kristijanhusak** [comment]
I pushed a fix. Pull latest version of vim-packager and give it a try.

**Comment by n0542344** [comment]
Awesome, thanks a lot - it works flawlessly!
