### ISSUE TITLE
Controlling load order

### ISSUE THREAD

**Issue by hermitmaster** [kristijanhusak/vim-packager#27]
I like the manager. Super light and works great. One question: Is there any way to control load order. For example vim-devicons must load before vim-startify for icons to work.

Thanks again!

**Comment by kristijanhusak** [comment]
Loading is done by Vim. Packager manages only install/update/delete.
You could install both of those into `opt` folder and load them manually:

```vim
function PackagerInit() 
call packager#add('... /vim-devicons', { 'type' : 'opt' }) 
call packager#add('... /vim-startify', { 'type' : 'opt' }) 
endfunction

packadd vim-devicons
packadd vim-startify
```
