### ISSUE TITLE
Configurable keybindings

### ISSUE THREAD

**Issue by deathlyfrantic** [kristijanhusak/vim-packager#9]
Would you consider making keybindings configurable in some way? I use `<C-j>` and `<C-k>` to move between windows and having them mapped to move between plugins here always trips me up. I could use some timer hackery to removing the bindings after they're set but that doesn't feel great.

**Comment by kristijanhusak** [comment]
Yeah that sounds ok. I'll probably create <Plug> mappings which will be set to some defaults that can be overriden.

**Comment by kristijanhusak** [comment]
@deathlyfrantic I added it. 
You can change the mapping using autocmd:

```
autocmd FileType packager nmap <buffer> new_next_mapping <Plug>(PackagerGotoNextPlugin)
autocmd FileType packager nmap <buffer> new_prev_mapping <Plug>(PackagerGotoPrevPlugin)
```

Give it a try and let me know if it works.

**Comment by deathlyfrantic** [comment]
Working fine for me. Thank you!
